### ISSUE TITLE
Sync tests with UglifyJS

### ISSUE THREAD

**Issue by Andarist** [fabiosantoscode/terser#34] opened 2018-05-17 15:23 UTC
It would be great to figure out how to sync this repo to newest developments on UglifyJS, having i.e. issues posted here automatically whenever commits with new tests are being added to the other repo.

**Comment by kzc** [comment] 2018-05-17 18:53
Duplicate of #5.

Short term some `uglify-js` fixes can be applied, but long term that may not necessarily be the case as the fork diverges. PRs with tests always welcome.

See also: #26

**Closed by kzc** 2018-05-17 18:53 UTC

**Comment by Andarist** [comment] 2018-05-17 19:44
Sorry if I was not clear - but I was proposing automation of some syncing process. I understand actual code sync is too hard to do automatically, but i.e. creating issues automatically about new tests being added (or changed) in the origina lrepo would be doable. Linked issue (and PR) is not about automating this in any form.

**Comment by kzc** [comment] 2018-05-17 20:25
People have to appreciate that this fork is not `uglify-js` and will have a different feature set and will not necessarily have the same optimizations. 

ES5 tests with `expect_stdout` can certainly be migrated over from `uglify-js`. If you wanted to automate that process with a script - by all means submit a PR. But sooner or later it will not be tenable as `uglify-js` diverges too much from this fork.

But since the forks are fairly compatible at this moment, to see if fixed `uglify-js` bugs exist in this fork, on a *temporary* test branch of this project one can:

1. `rm -rf test/compress`
2. copy the same directory from `uglify-js` `master` in its place
3. apply the patch below
4. run `npm test`:

```patch
--- a/test/run-tests.js
+++ b/test/run-tests.js
@@ -160,7 +160,7 @@ function run_compress_tests() {
                 }
             }
             output = make_code(output, output_options);
-            if (expect != output) {
+            if (0 && expect != output) {
                 log("!!! failed\n---INPUT---\n{input}\n---OUTPUT---\n{output}\n---EXPECTED---\n{expected}\n\n", {
                     input: input_formatted,
                     output: output,
@@ -189,7 +189,7 @@ function run_compress_tests() {
                     return input.split(process.cwd() + path.sep).join("").split(path.sep).join("/");
                 });
                 var actual_warnings = JSON.stringify(warnings_emitted);
-                if (expected_warnings != actual_warnings) {
+                if (0 && expected_warnings != actual_warnings) {
                     log("!!! failed\n---INPUT---\n{input}\n---EXPECTED WARNINGS---\n{expected_warnings}\n---ACTUAL WARNINGS---\n{actual_warnings}\n\n", {
                         input: input_formatted,
                         expected_warnings: JSON.parse(expected_warnings).join('\n'),
```
This will determine whether the `uglify-js` `expect_stdout` tests pass under various `minify()` options and ignore the rest of the tests. This is how #26 was put together.

**Comment by kzc** [comment] 2018-05-19 21:43
@Andarist FWIW I manually merged the `expect_stdout` tests from `uglify-js` in #35. The other tests are not as interesting/useful to this fork.
