### ISSUE TITLE
readme suggestion

### ISSUE THREAD

**Issue by transitive-bullshit** [fabiosantoscode/terser#54] opened 2018-06-14 16:20 UTC
It took me awhile to understand how this project relates to the existing uglify ecosystem. Currently, users have to dig a bit and read through #2 which is quite unintuitive.

It'd be amazing if a concise summary were added to the header of `terser`'s readme, explaining how this project is meant to take over for the unmaintained `uglify-*`.

**Comment by kzc** [comment] 2018-06-14 16:27
duplicate of #53

**Closed by kzc** 2018-06-14 16:27 UTC

**Comment by transitive-bullshit** [comment] 2018-06-14 16:39
@kzc this is not a duplicate of #53. The entire point is to make this information along with a **concise** recommendation readily available at the top of the readme.

There will be an increasing number of devs who end up here in the coming months, and it's a really poor experience right now to have to dig through issues like #2 and #53 to figure out what will be on everyone's mind.

Please add a more concise version of #53 to the readme.

**Comment by Martii** [comment] 2018-06-14 19:21
Nice username reporter... anyhow @kzc it would be agreeable to have what you said in a mission statement in a wiki page, with perhaps a singular reference link somewhere else... although I've already investigated this myself for our project and we're anxious and willing. :)

**Comment by kzc** [comment] 2018-06-15 15:43
README updated: https://github.com/fabiosantoscode/terser/commit/3ef6879ecafd12b57e575ec85e6104e71d5a1b6f

Thanks.

**Comment by olsonpm** [comment] 2018-06-15 15:45
Sorry I would have created a PR - I just wasn't sure you guys would be for it.

**Comment by kzc** [comment] 2018-06-15 16:50
@olsonpm No worries. I just wanted to keep the description brief and critiquing a PR would have taken more time than just making the doc change.
