### ISSUE TITLE
Project naming and organization

### ISSUE THREAD

**Issue by guybedford** [fabiosantoscode/terser#2] opened 2018-04-23 16:57 UTC
It would be nice to have a simple npm name to install this project going forward, as well as a generic organization repo that can have multiple maintainers working on it. @fabiosantoscode would you be open to these directions?

For a name, I thinks it's worth keeping the "uglify" part (brand has existing value!), but then coming up with a unique prefix or suffix to distinguish it entirely separately without seeming like it is a "competing project".

I'm actually tending towards calling it _uglify3_ I must admit, but other suggestions welcome.

**Comment by guybedford** [comment] 2018-04-23 16:58
Perhaps less competing would be `uglify-eg` for "evergreen".

**Comment by guybedford** [comment] 2018-04-23 16:59
Or even `uglify-edge`.

**Comment by fabiosantoscode** [comment] 2018-04-23 17:03
I like "uglify-edge" too. Let's have some more opinions!

**Comment by TrySound** [comment] 2018-04-23 17:17
"Edge" is associated with browser. Maybe something like "Uglify: Homecoming"?

**Comment by Rich-Harris** [comment] 2018-04-23 17:44
I wonder if the `uglify-es` name has become somewhat tainted — someone Googling for it could easily come across tweets and GitHub issues describing it as no longer maintained, which could be a little confusing.

What if the name was similar enough that it kept some of the 'brand' associations, but was different enough that there was no possibility of confusion? Depending on how far the projects end up diverging, that could prove to be a benefit in the long run. `uglifier` and `ugliest` are both available on npm, for example.

**Comment by TrySound** [comment] 2018-04-23 17:47
I just would like to migrate to the new package in `rollup-plugin-uglify` and save name.

**Comment by fabiosantoscode** [comment] 2018-04-23 18:02
We could use uglify3. And possibly change the CLI name.

**Comment by arackaf** [comment] 2018-04-23 18:28
I really think you guys should avoid the uglify name completely at this point.  We already literally have uglifyjs, uglifyjs2, and there's even an uglifyjs 3.  And now of course the abandoned uglify-es.

Why not es-minify?

**Comment by kzc** [comment] 2018-04-23 18:29
**-1** on `uglify-edge` - due to Microsoft browser connotation.

> I'd definitely avoid numbers

Complete agreement there.

As for all the other `uglify*` variants, I think there ought to be a clean break and remove `uglify` from the name altogether. We don't want to confuse it with the original project. If it's a fork, then really make it a fork. And take the opportunity to have the binary in the `bin` directory match the package name.

**Comment by boris-petrov** [comment] 2018-04-23 18:35
Just a note - a lot of projects depend on `uglify-es`. Most indirectly by using some FE framework (Ember uses `broccoli-uglify-sourcemap` for example). Forking and changing the name would require all of them to switch to the new project. I wouldn't expect that to happen any time soon, especially for major frameworks/build-systems like Ember/Broccoli, Angular/Webpack, etc.

For me the "right" way is to continue the same project (`uglify-es`) just with different maintainers. It's a real pity that this can't happen for now.

**Comment by arackaf** [comment] 2018-04-23 18:38
It's still not entirely clear to me why new maintainers can't just be added to this existing project, uglify-es.  What exactly is the problem?  It's incredibly common for maintainers who want to move on to grant rights to new folks who are willing to pick up the slack.

**Comment by guybedford** [comment] 2018-04-23 18:41
I believe the reason here is that the current maintainer wants a clean separation between the project branding. So far he's indicating he doesn't want to share the npm publish rights for these reasons. So long as that remains the case, new branding is required.

@alexlamsl otherwise, perhaps if the CLI bin was changed to `uglify-es` as well, would that help create a clean separation to keep using the uglify-es name?

Without access to the same npm name, yes users need to update their dependencies. The idea of sticking close to `uglify` name was to minimize the rebranding issues associated with this process.

**Comment by arackaf** [comment] 2018-04-23 18:51
If for some unfortunate reason existing maintainers are unwilling to let new maintainers take over, then yes, the break should be obvious and clear.  The many projects currently depending on uglify-es (webpack, etc) will just have to change their configs.  Sucks, but it is what it is.

**Comment by guybedford** [comment] 2018-04-24 13:33
It makes sense not to limit to uglify-based names if doing the rebranding, and once the main projects catch on it shouldn't be too much of an issue actually.

I really like `shrink` actually. If the npm name isn't available we could always use the `shrinkjs` name eg: `npm install -g shrinkjs && shrink x.js`.

**Comment by arackaf** [comment] 2018-04-24 13:36
shrink-js and shrink-es both appear to be available.  Someone jump on them! :)

**Comment by kzc** [comment] 2018-04-24 14:02
One of the names that @Rich-Harris suggested would be fine, or something along those lines.

I'd suggest not to use a dash (`-`) in the name which would have to be changed to an underscore in a variable naming context. Also, using `js` in the name is unnecessary and redundant in my opinion - the `js` gets dropped in discussions about the module. A uniquely google-able name would be ideal.

**Comment by Rich-Harris** [comment] 2018-04-24 14:07
[shrink](https://www.npmjs.com/package/shrink) is a package that was last published 6 years ago (version 0.0.3) and has zero weekly downloads. Let's ask npm if they'll give it to us — they usually do in these situations.

**Comment by guybedford** [comment] 2018-04-24 14:53
I've emailed the shrink package owner about this.

**Comment by tomcon** [comment] 2018-04-24 15:40
> Why not es-minify? 

I like es-minify, otherwise snugly?

**Comment by guybedford** [comment] 2018-04-24 15:45
esminify already exists - https://www.npmjs.com/package/esminify.

**Comment by fabiosantoscode** [comment] 2018-04-24 15:49
esmin too :(

**Comment by fabiosantoscode** [comment] 2018-04-24 15:50
How about we compress the vowels out of "uglify" and come up with "glfjs"?

**Comment by tomcon** [comment] 2018-04-24 16:02
> shrink is a package that was last published 6 years ago (version 0.0.3) and has zero weekly downloads. Let's ask npm if they'll give it to us — they usually do in these situations.

shrinker was a very popular niche package performing a similar job for executable files way back

**Comment by kzc** [comment] 2018-04-24 19:13
The downside with the package name `shrink` is that it is not unique nor easily googled. It's also a bit boring.

I'll defer the naming of this fork to @fabiosantoscode.

**Comment by Rich-Harris** [comment] 2018-04-24 19:31
I'm not sure it's such a problem, when you look at the most popular packages — react, angular, babel, bluebird, moment, express, chalk, request — all very common English words. I think people are used to either searching npm directly or adding 'js' or 'javascript'.

The nice thing about a word like 'shrink' is that it's a verbal command — something rather satisfying about 

```bash
shrink my-file.js
```

and the computer complying. (And now that people use `npx`, there's definitely value in the package name matching the bin.)

**Comment by guybedford** [comment] 2018-04-24 19:33
This is why I would adocate `ShrinkJS/shrink` as the GitHub repo name - ensures it can be easily found in search.

**Comment by arackaf** [comment] 2018-04-24 19:45
> I think people are used to either searching npm directly or adding 'js' or 'javascript'.

I second this strongly.   It's a non-issue in practice.

**Comment by kzc** [comment] 2018-04-24 20:00
`shrink` just ain't doing it for me.

Some other package name suggestions that are available at this moment from most to least preferred:

* terser
* compendious
* epitomize
* condensed
* succinctify

**Comment by fabiosantoscode** [comment] 2018-04-24 21:03
I like es-shrink a lot!

**Comment by fabiosantoscode** [comment] 2018-04-28 19:12
How about we gain access to uglify-es? It already has such a large following..

@alexlamsl would you consider releasing the "uglify-es" package name on NPM?

**Comment by arackaf** [comment] 2018-04-28 19:32
I think we went through this already.  If they were going to do that, then they'd just make you a core contributor to the project it self, with publish rights.  

Disconcertingly they seem unwilling to do so :(

**Comment by guybedford** [comment] 2018-04-29 10:05
Finally heard back that the `shrink` package name is actually being used, so it sounds like `es-shrink` might be the better option here, but perhaps then still using `shrink` as the bin name.

**Comment by kzc** [comment] 2018-04-29 14:38
Whatever the package name, please have the `bin/` script name match it to reduce confusion.

Uglify is a mess with `uglify-js` as the package name and `uglifyjs` as the CLI name. (Ignoring the fact that `uglify-es` was intended to be the successor of `uglify-js` so confusingly it also retained the `uglifyjs` bin name.)

I'll make one last appeal for the package name `terser` - it's a play on `prettier`.

**Comment by guybedford** [comment] 2018-05-12 13:11
@kzc I get where you're coming from here on both points.

For a play on prettier - `denser` is nice and **available.**

Also if we want to have a connection to the history of the project (uglify), `densify` **is also available!**.

I think it's important to move forward with the branding here. Can we please have a final vote then get this moving?

**Comment by Rich-Harris** [comment] 2018-05-12 13:31
Someone named Vasily Anonimov has just claimed es-shrink, terser, denser and densify: https://www.npmjs.com/~vasily.anonimov. Vasily, who are you?

**Comment by guybedford** [comment] 2018-05-12 13:43
I guess the first thing to work out is if this is malice, or someone kindly moving this forward for us :)

If it really is malice, we can file an npm ticket and get it removed easily. Since these were created just after my post, I've noted all watchers of this repo, and it's quite simple to rule out who it is as well from this.

Let's please move forward with a vote - getting the npm name should still be fine regardless.

**Comment by Rich-Harris** [comment] 2018-05-12 13:48
I'm good with either terser or denser. `terser` is a particularly fun word to type! I think it's possibly more distinctive than denser as well, since it's not in common usage (despite having a well-understood meaning).

**Comment by kzc** [comment] 2018-05-12 16:42
> we can file an npm ticket and get it removed easily

Not necessarily. It took several months for the uglify project to claim the the npm module name `uglifyjs`. And there it was a clear cut case of someone publishing an old version of `uglify-js`.

Probably best to claim the npm module name first, then suggest it.

Or better yet, @fabiosantoscode just find an available name you like and use it. At the end of the day, the package name is arbitrary. But before the new name is cutover please publish another version of `@fabiosantoscode/uglify-es` to get the upstream ES5 bug fixes just committed.

**Comment by Rich-Harris** [comment] 2018-05-12 17:34
I've emailed Vasily Anonimov and cc'd npm. Quoting the terms of service:

> It is against npm's Terms of Use to publish a package, register a user name or an organization name simply for the purposes of reserving it for future use. If a package matches our criteria for squatting we will transfer it to another user who asks for it; this is immediate and does not follow the 4-week process outlined for normal transfer requests above.

Hopefully this will get resolved on Monday when npm support sees it.

**Comment by fabiosantoscode** [comment] 2018-05-12 18:38
Let's go with terser. Thanks for looking into the Vasily situation, it should be no trouble to have the package removed. Although I had problems with npm before. I published a package called yourmom. It was several gigabytes large.

**Comment by fabiosantoscode** [comment] 2018-05-15 14:16
We didn't get the name yet :(

**Comment by Rich-Harris** [comment] 2018-05-15 14:18
Yeah, I haven't heard back from npm. Maybe today

**Comment by fabiosantoscode** [comment] 2018-05-17 12:40
Terser is the new package name! Thanks @Rich-Harris for giving me ownership to it. Vasily has been removed as an owner.

**Comment by kzc** [comment] 2018-05-17 12:55
> Vasily has been removed as an owner.

He is still listed as a maintainer and a collaborator:

https://www.npmjs.com/package/terser

```
$ npm show terser
 
{ name: 'terser',
  'dist-tags': { latest: '3.7.2' },
  versions: [ '0.0.1', '1.0.0', '3.7.1', '3.7.2' ],
  time: 
   { created: '2018-05-12T13:21:59.686Z',
     '1.0.0': '2018-05-12T13:21:59.752Z',
     modified: '2018-05-17T12:41:05.219Z',
     '0.0.1': '2018-05-17T11:56:02.951Z',
     '3.7.1': '2018-05-17T12:37:32.239Z',
     '3.7.2': '2018-05-17T12:41:00.795Z' },
  maintainers: 
   [ 'fabiosantoscode <fabiosantosart@gmail.com>',
     'vasily.anonimov <vasily.anonimov@googlemail.com>' ],
```
Can Vasily be removed from the project? We don't want the possibility of him publishing.

**Comment by ojab** [comment] 2018-05-17 12:57
Would you mind to drop a line into https://github.com/webpack-contrib/uglifyjs-webpack-plugin/issues/262?

**Comment by kzc** [comment] 2018-05-17 13:14
@fabiosantoscode

```
npm owner rm <user> [<@scope>/]<pkg>
```

https://docs.npmjs.com/cli/owner

**Comment by TrySound** [comment] 2018-05-17 13:39
Don't let Vasiliy break our future. :)

**Comment by fabiosantoscode** [comment] 2018-05-17 14:13
I can't remove him from the maintainer list though.

**Comment by Martii** [comment] 2018-05-17 17:52
> Can Vasily be removed from the project? We don't want the possibility of him publishing.

This would be a good thing to see removed if it's not authorized officially.

@fabiosantoscode 
Is there some reason why https://www.npmjs.com/~vasily.anonimov has almost all the upvoted names mentioned in here? *(e.g. check with `npm show es-shrink version` to see if squatting)*

**Comment by Rich-Harris** [comment] 2018-05-17 18:15
> Is there some reason why https://www.npmjs.com/~vasily.anonimov has almost all the upvoted names mentioned in here?

Yes, the reason is that he's a squatter, who apparently has nothing better to do than waste the time and energy of people trying to contribute to the JavaScript community. Those packages were registered within minutes of [this comment](https://github.com/fabiosantoscode/terser/issues/2#issuecomment-388554263), and only have a package.json. If npm were to uphold their stated policies those packages would have been removed by now.

Vasily, if I'm misrepresenting you, feel free to chime in since you're obviously lurking on this thread.

(@fabiosantoscode I sent you an email earlier today, let me know if you didn't receive it!)

**Comment by kzc** [comment] 2018-05-17 18:25
Reopening ticket until the `terser` maintainer/owner issue is resolved.

**Comment by fabiosantoscode** [comment] 2018-05-18 09:46
I've sent a support ticket. Maybe it will be faster since I'm registered as the package owner.

**Comment by Martii** [comment] 2018-05-18 23:52
Is it truly fixed today? See https://www.npmjs.com/package/terser

**Comment by Rich-Harris** [comment] 2018-05-18 23:57
Looks that way!

```bash
$ npm owner ls terser
fabiosantoscode <fabiosantosart@gmail.com>
```

Hopefully this is the last time anyone in the JavaScript community has to deal with Vasily Anonimov.

**Comment by kzc** [comment] 2018-05-19 00:25
He still appears in `npm show terser`:
```
  maintainers: 
   [ 'fabiosantoscode <fabiosantosart@gmail.com>',
     'vasily.anonimov <vasily.anonimov@googlemail.com>' ],
```
I am not well versed in `npm`. Are we certain he is not able to publish?

**Comment by Martii** [comment] 2018-05-19 02:51
@kzc

> Are we certain he is not able to publish?

Might be a bug in their metadata... might disappear on a new publish *(related to metadata)*... but to be sure their repo with the Issue tracker is at https://github.com/npm/www for those maintaining this project.

**Comment by fabiosantoscode** [comment] 2018-06-01 21:47
Npm support replied later the same day. The issue has been resolved.

**Closed by fabiosantoscode** 2018-06-01 21:47 UTC

**Comment by kzc** [comment] 2018-06-01 23:07
@fabiosantoscode Can you ask Npm to remove the name squatter from `terser` maintainers?

```
  maintainers: 
   [ 'fabiosantoscode <fabiosantosart@gmail.com>',
     'vasily.anonimov <vasily.anonimov@googlemail.com>' ],
```

**Comment by fabiosantoscode** [comment] 2018-06-02 09:16
@kzc I'll ask. 

It looks like he appears on "npm show terser maintainers" but not on "npm show terser". Is this your issue too?

**Comment by fabiosantoscode** [comment] 2018-06-02 09:26
@Martii what is your node version exactly?

**Comment by Martii** [comment] 2018-06-02 09:27
@fabiosantoscode 

``` sh-console
$ node -v
v8.11.2
```

**Comment by fabiosantoscode** [comment] 2018-06-02 09:30
Ok, I can indeed reproduce your findings. I'll include them in my ticket to npm.

**Comment by kzc** [comment] 2018-06-02 12:04
That did the trick.

I guess we can't remove the squatter's first two package versions?

```
$ npm show terser versions
 
[ '0.0.1',
  '1.0.0',
```

**Comment by Martii** [comment] 2018-06-02 18:54
@kzc 

> I guess we can't remove the squatter's first two package versions?

Probably not in case something depends on it whether public or private. npmjs.com is pretty clear about that with the instance where a project was deleted and it broke a bunch of other packages... even if those versions are junk squatting.

There's plenty of documentation on this package now that someone can read up on it and make an educated, secure, decision in favor of using it at the latest revision. 

Appreciate what you guys have done to ensure the security of this package. :)
